- hosts: testhost
  gather_facts: no
  tasks:
    - name: ping with wrong arg
      ping: wrong_k=v
      tags:
        - failed

    - name: ping with wrong arg (ignore_errors)
      ping: wrong_k=v
      ignore_errors: yes
      tags:
        - failed_ignore

    - name: ping with wrong arg (retries)
      ping: wrong_k=v
      register: result
      until: result.failed == False
      retries: 2
      delay: 1
      tags:
        - failed_retries

    - name: ping with wrong arg (retries, ignore_errors)
      ping: wrong_k=v
      register: result
      until: result.failed == False
      retries: 2
      delay: 1
      ignore_errors: yes
      tags:
        - failed_retries_ignore_errors

    - name: invalid rc
      command: ls non_exist_directory
      tags:
        - invalid_rc

    - name: invalid rc (ignore_errors)
      command: ls non_exist_directory
      ignore_errors: yes
      tags:
        - invalid_rc_ignore_errors

    - name: no module
      action: pi
      tags:
        - no_module

    - name: env is not dict
      ping:
      environment:
        - k: v
      tags:
        - env_is_not_dict

    - name: action plugin throws error
      assert:
        that:
          - "undefined_var"
      tags:
        - action_plugin_throws_error

    - name: use undefined var in template
      ping: data={{ undefined_var }}
      tags:
        - undefined_var_in_template

    - name: use wrong filter in template
      ping: data={{ ['a', 'b'] | wrong_filter }}
      tags:
        - wrong_filter_in_template

    - name: when keyword has error
      ping:
      when: undefined_var
      tags:
        - when_keyword_has_error

    - name: duplicate arguments
      ping: data=a data=b
      tags:
        - duplicate_arguments

    - name: failed_when
      ping: data=a
      failed_when: True
      tags:
        - failed_when

    - name: failed_when (ignore_errors)
      ping: data=a
      failed_when: True
      ignore_errors: yes
      tags:
        - failed_when_ignore_errors

- hosts: unreachable_host
  gather_facts: no
  tasks:
    - name: send unreachable ping
      ping:
      tags:
        - unreachable

    - name: send unreachable ping (ignore_errors)
      ping:
      ignore_errors: yes
      tags:
        - unreachable_ignore_errors

- hosts: wrong_port_host
  gather_facts: no
  tasks:
    - name: wrong port
      ping:
      tags:
        - wrong_port

    - name: wrong port (ignore_errors)
      ping:
      ignore_errors: yes
      tags:
        - wrong_port_ignore_errors

- hosts: unreachable_host_paramiko
  gather_facts: no
  tasks:
    - name: send unreachable ping
      ping:
      tags:
        - unreachable_paramiko

    - name: send unreachable ping (ignore_errors)
      ping:
      ignore_errors: yes
      tags:
        - unreachable_paramiko_ignore_errors
